plugins {
	id "com.crystaelix.loom" version "1.9.0"
	id "eclipse"
	id "idea"
	id "maven-publish"
	id "net.kyori.blossom" version "[1,2)"
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

repositories {
	mavenCentral()
	flatDir {
		dirs "libs"
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.parchmentmc.net/"
			}
		}
		filter {
			includeGroup "org.parchmentmc.data"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.blamejared.com/"
			}
		}
		filter {
			includeGroup "mezz.jei"
			includeGroup "com.blamejared.crafttweaker"
			includeGroup "blusunrize.immersiveengineering"
			includeGroup "net.darkhax.bookshelf"
			includeGroup "net.darkhax.pricklemc"
			includeGroup "net.darkhax.openloader"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.theillusivec4.top/"
			}
		}
		filter {
			includeGroup "top.theillusivec4.curios"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.architectury.dev/"
			}
		}
		filter {
			includeGroup "dev.architectury"
			includeGroup "me.shedaniel.cloth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.saps.dev/releases/"
			}
		}
		filter {
			includeGroup "dev.ftb.mods"
			includeGroup "dev.latvian.mods"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.createmod.net/"
			}
		}
		filter {
			includeGroup "com.simibubi.create"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
			}
		}
		filter {
			includeGroup "software.bernie.geckolib"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dogforce-games.com/maven/"
			}
		}
		filter {
			includeGroup "dev.gigaherz.jsonthings"
			includeGroup "dev.gigaherz.graph"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dl.cloudsmith.io/public/tslat/sbl/maven/"
			}
		}
		filter {
			includeGroup "net.tslat.smartbrainlib"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
			}
		}
		filter {
			includeGroup "com.klikli_dev"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://nexus.themcbrothers.net/repository/maven-releases/"
			}
		}
		filter {
			includeGroup "net.themcbrothers"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://maven.rover656.dev/releases/"
			}
		}
		filter {
			includeGroup "com.enderio"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://cursemaven.com/"
			}
		}
		filter {
			includeGroup "curse.maven"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://api.modrinth.com/maven/"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				url = "https://modmaven.dev/"
			}
		}
		filter {
			includeGroup "mekanism"
			includeGroup "dev.technici4n"
			includeGroup "aztech"
		}
	}
}

sourceSets {
	main
}

def mcVersion = "1.21.1"
def modName = "JAOPCA"
def modId = "jaopca"
def specVersion = "5"
def vendor = "thelm"

group = "thelm.jaopca"
version = "5.0.7.9"

archivesBaseName = "${modName}-${mcVersion}"

java {
	toolchain.languageVersion = JavaLanguageVersion.of(21)
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

loom {
	silentMojangMappingsLicense()
	interfaceInjection.enableDependencyInterfaceInjection = false
	runs {
		configureEach {
			property "forge.logging.console.level", "debug"
		}
		client {
			vmArg "-Xmx7G"
		}
		server {
			vmArg "-Xmx3G"
		}
	}
}

dependencies {
	// Log4j
	implementation "org.apache.logging.log4j:log4j-core:2.24.1"

	// Minecraft
	minecraft "com.mojang:minecraft:1.21.1"
	mappings loom.layered {
		officialMojangMappings()
		parchment "org.parchmentmc.data:parchment-1.21:2024.07.28@zip"
	}
	neoForge "net.neoforged:neoforge:21.1.132"

	// Common
	implementation("mezz.jei:jei-1.21.1-neoforge:19.21.0.247") {transitive = false}
	implementation "top.theillusivec4.curios:curios-neoforge:9.2.2+1.21.1"
	implementation("software.bernie.geckolib:geckolib-neoforge-1.21.1:4.7.3") {transitive = false}
	implementation("com.klikli_dev:modonomicon-1.21.1-neoforge:1.112.2") {transitive = false}
	implementation "dev.architectury:architectury-neoforge:13.0.8"
	implementation "dev.latvian.mods:rhino:2101.2.7-build.74"

	// CraftTweaker
	implementation("com.blamejared.crafttweaker:CraftTweaker-neoforge-1.21.1:21.0.22") {transitive = false}

	// KubeJS
	implementation("dev.latvian.mods:kubejs-neoforge:2101.7.1-build.181") {transitive = false}

	// Json Things
	modImplementation("dev.gigaherz.jsonthings:JsonThings-1.21.1:0.13.2") {transitive = false}

	// Open Loader
	implementation "net.darkhax.bookshelf:bookshelf-neoforge-1.21.1:21.1.48"
	implementation "net.darkhax.pricklemc:prickle-neoforge-1.21.1:21.1.6"
	implementation "net.darkhax.openloader:openloader-neoforge-1.21.1:21.1.1"

	// Actually Additions
	implementation "curse.maven:actually-additions-228404:6193603"

	// Create
	implementation("com.simibubi.create:create-1.21.1:6.0.2-36") {transitive = false}

	// Electrodynamics
	implementation "curse.maven:electrodynamics-316867:6199591"

	// Ender IO
	implementation "com.enderio:enderio-machines:7.1.6-alpha"

	// Energized Power
	implementation "curse.maven:energized-power-782147:5797585"

	// Immersive Engineering
	implementation "blusunrize.immersiveengineering:ImmersiveEngineering:1.21.1-12.1.0-185"

	// Integrated Dynamics
	implementation "curse.maven:cyclops-core-232758:6230091"
	implementation "curse.maven:common-capabilities-247007:6173956"
	implementation "curse.maven:integrated-dynamics-236307:6221696"

	// Mekanism
	implementation "mekanism:Mekanism:1.21.1-10.7.9.72"

	// Modern Industrialization
	implementation "me.shedaniel.cloth:cloth-config-neoforge:15.0.140"
	implementation "dev.technici4n:GrandPower:3.0.2"
	implementation("aztech:Modern-Industrialization:2.2.34") {transitive = false}

	// Occultism
	implementation "net.tslat.smartbrainlib:SmartBrainLib-neoforge-1.21.1:1.16.7"
	implementation("com.klikli_dev:occultism-1.21.1-neoforge:1.176.0") {transitive = false}

	// Railcraft Reborn
	implementation "curse.maven:railcraft-reborn-901491:6149952"

	// Theurgy
	implementation("com.klikli_dev:theurgy-1.21.1-neoforge:1.60.0") {transitive = false}

	// Useful Machinery
	implementation "net.themcbrothers:themcbroslib:1.21.1-8.1.0"
	implementation "net.themcbrothers:useful-foundation:1.21-1.0.0"
	implementation("net.themcbrothers:useful-machinery:1.21-1.0.0") {transitive = false}

	// Testing
	implementation "curse.maven:ato-405593:6118610"
	implementation "curse.maven:allthemodium-364466:6135138"

	// Performance
	implementation "curse.maven:yeetusexperimentus-635427:5444189"
	implementation "curse.maven:modernfix-790626:6125147"
	implementation "curse.maven:ferritecore-429235:5850121"
}

def replacements = [
	"0@VERSION@": version,
	"9@VERSION@": version,
]

blossom {
	replaceToken(replacements)
}

processResources {
	inputs.properties(replacements)
	filesMatching(["mcmod.info", "META-INF/mods.toml", "META-INF/neoforge.mods.toml"]) {
		filter {
			it.replace(replacements)
		}
	}
}

def manifestAttributes = [
	"Specification-Title": modName,
	"Specification-Vendor": vendor,
	"Specification-Version": specVersion,
	"Implementation-Title": archivesBaseName,
	"Implementation-Version": version,
	"Implementation-Vendor": vendor
]

jar {
	manifest.attributes(manifestAttributes)
}

sourcesJar {
	manifest.attributes(manifestAttributes)
}

publishing {
	publications {
		register("mavenJava", MavenPublication) {
			artifact remapJar
			artifact sourcesJar
		}
	}
	repositories {
		if(project.hasProperty("CrystaelixMavenUsername") && project.hasProperty("CrystaelixMavenPassword")) {
			maven {
				name = "CrystaelixMaven"
				url = "https://maven.crystaelix.com/releases/"
				credentials(PasswordCredentials)
			}
		}
	}
}

def curseforgeDependencies = [
	"actually-additions",
	"crafttweaker",
	"create",
	"electrodynamics",
	"ender-io",
	"energized-power",
	"immersive-engineering",
	"integrated-dynamics",
	"json-things",
	"kubejs",
	"mekanism",
	"modern-industrialization",
	"occultism",
	"open-loader",
	"railcraft-reborn",
	"theurgy",
	"useful-machinery"
]

def modrinthDependencies = [
	"actually-additions",
	"crafttweaker",
	"create",
	"electrodynamics",
	"enderio",
	"energized-power",
	"immersiveengineering",
	"integrated-dynamics",
	"kubejs",
	"mekanism",
	"modern-industrialization",
	"occultism",
	"open-loader",
	"railcraft-reborn",
	"theurgy",
	"useful-machinery"
]

publishMods {
	file = remapJar.archiveFile
	version = displayName = "${mcVersion}-${project.version}"
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("neoforge")
	additionalFiles.from(sourcesJar.archiveFile)

	curseforge {
		accessToken = providers.gradleProperty("curseforge.token")
		projectId = "266936"
		minecraftVersions.add(mcVersion)
		optional curseforgeDependencies as String[]
	}

	modrinth {
		accessToken = providers.gradleProperty("modrinth.token")
		projectId = "P48mHi2j"
		minecraftVersions.add(mcVersion)
		optional modrinthDependencies as String[]
	}
}
