modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/JAOPCA/issues"

[[mods]]
	modId = "jaopca"
	version = "0@VERSION@"
	displayName = "JAOPCA"
	description = "A mod that aims to make mods with ore processing support more ores."
	logoFile = "jaopca.logo.png"
	credits = "Inspired by AOBD, a mod by ganymedes01"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/jaopca"

[[dependencies.jaopca]]
	modId = "forge"
	versionRange = "[40,)"
	mandatory = true
